### ISSUE TITLE
Баг из-за которого использовать мод невозможно

### ISSUE THREAD

**Issue by ghost** [Tervinter/GameUtils#1]
![image](https://user-images.githubusercontent.com/49371872/116921935-18f4ab80-ac6e-11eb-86f5-8def787c32e6.png)

**Comment by NoAJPL** [comment]
пошел нахуй)

**Comment by ghost** [comment]
фикси заебал

**Comment by NoAJPL** [comment]
ща блять тервинтеру напишу он нахуй этот репо снесет и все

**Comment by ghost** [comment]
схуяле

**Comment by ghost** [comment]
а куда багрепорты кидать

**Comment by NoAJPL** [comment]
хуй знает))

**Comment by NoAJPL** [comment]
# Ебать тут маркдовн есть а я не знал)))

**Comment by NoAJPL** [comment]
# [Ебать](http://pornhub.com/gayporn)

**Comment by ghost** [comment]
ну нажал случайно ctrl + v
с кем не бывает

**Comment by ghost** [comment]
а я вот любимые сайты в закладках храню
